/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated student's profile. */
        get: operations["getProfile"];
        /** Create or fully replace the authenticated student's profile. */
        put: operations["replaceProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List private documents owned by the authenticated student. */
        get: operations["listProfileDocuments"];
        put?: never;
        /** Upload a private profile document for asynchronous processing. */
        post: operations["uploadProfileDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/documents/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authoritative private-document upload policy. */
        get: operations["getDocumentUploadPolicy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/documents/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Map required scholarship documents to private user documents.
         * @description Mapping never shares a file with a scholarship provider.
         */
        get: operations["getDocumentReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Replace the bytes of a private document while retaining its identity. */
        put: operations["replaceProfileDocument"];
        post?: never;
        /** Permanently delete a private document after explicit confirmation. */
        delete: operations["deleteProfileDocument"];
        options?: never;
        head?: never;
        /** Rename a private document's display name. */
        patch: operations["renameProfileDocument"];
        trace?: never;
    };
    "/profile/documents/{document_id}/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a short-lived signed download URL for one private document.
         * @description Permanent object URLs and storage paths are never returned.
         */
        post: operations["createDocumentDownloadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scholarships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List published scholarships.
         * @description Searches title, provider, field of study, and the normalized description.
         *     Results include the authenticated student's saved state and current
         *     eligibility assessment. Funding-amount sorting only compares records
         *     whose amount and currency are directly comparable.
         */
        get: operations["listScholarships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scholarships/{scholarship_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one published scholarship. */
        get: operations["getScholarship"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scholarships/{scholarship_id}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List related published scholarships from the current catalogue. */
        get: operations["listRelatedScholarships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scholarships/{scholarship_id}/saved": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scholarship_id: components["parameters"]["ScholarshipId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Save a scholarship for the authenticated student. */
        put: operations["saveScholarship"];
        post?: never;
        /** Remove a scholarship from the authenticated student's saved list. */
        delete: operations["unsaveScholarship"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scholarships/{scholarship_id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report potentially inaccurate scholarship information. */
        post: operations["reportScholarship"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List ranked matches for the authenticated student. */
        get: operations["listMatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/recalculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue a match recalculation for the authenticated student. */
        post: operations["recalculateMatches"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/recalculation-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the status of a match recalculation job. */
        get: operations["getMatchRecalculationJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{scholarship_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated student's match for one scholarship. */
        get: operations["getMatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{scholarship_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record structured feedback about one match explanation.
         * @description Feedback is reviewed and evaluated; submission does not immediately retrain a model.
         */
        post: operations["createMatchFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List applications owned by the authenticated student. */
        get: operations["listApplications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/deadlines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List calendar-friendly deadlines for tracked applications. */
        get: operations["listApplicationDeadlines"];
        put?: never;
        /** Start tracking an application. */
        post: operations["createApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update mutable application tracking fields. */
        patch: operations["updateApplication"];
        trace?: never;
    };
    "/applications/{application_id}/checklist/{checklist_item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set one checklist item's completion state. */
        put: operations["updateApplicationChecklistItem"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}/reminder": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Create or replace a private application reminder. */
        put: operations["setApplicationReminder"];
        post?: never;
        /** Remove an application reminder. */
        delete: operations["deleteApplicationReminder"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/ingestion-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Queue a scholarship ingestion run.
         * @description Requires a verified JWT with the application admin role.
         */
        post: operations["createIngestionRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/ingestion-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one ingestion run and its counters.
         * @description Requires a verified JWT with the application admin role.
         */
        get: operations["getIngestionRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: {
                /** @example VALIDATION_ERROR */
                code: string;
                /** @description Safe, human-readable summary. */
                message: string;
                /**
                 * @description Safe structured details; empty when no field-specific detail exists.
                 * @default []
                 */
                details: {
                    code: string;
                    field?: string | null;
                    message?: string | null;
                }[];
                /** Format: uuid */
                request_id: string;
            };
        };
        Pagination: {
            /** @description Opaque cursor for the next page; null on the final page. */
            next_cursor: string | null;
            has_more: boolean;
            limit: number;
        };
        ProfileWrite: {
            full_name: string;
            /** @description ISO 3166-1 alpha-2 code. */
            country: string;
            /** @enum {string} */
            study_level: "undergraduate" | "postgraduate" | "doctoral" | "other";
            field_of_study?: string | null;
            gpa?: number | null;
            interests: string[];
            goals?: string | null;
        };
        ProfileResponse: {
            /** Format: uuid */
            id: string;
            full_name: string;
            /** @description ISO 3166-1 alpha-2 code. */
            country: string;
            /** @enum {string} */
            study_level: "undergraduate" | "postgraduate" | "doctoral" | "other";
            field_of_study?: string | null;
            gpa?: number | null;
            interests: string[];
            goals?: string | null;
            /**
             * Format: date-time
             * @description UTC ISO-8601 timestamp.
             */
            created_at: string;
            /**
             * Format: date-time
             * @description UTC ISO-8601 timestamp.
             */
            updated_at: string;
        };
        /** @enum {string} */
        DocumentType: "transcript" | "cv" | "recommendation_letter" | "personal_statement" | "identity_document" | "financial_document" | "other";
        DocumentResponse: {
            /** Format: uuid */
            id: string;
            document_type: components["schemas"]["DocumentType"];
            display_name: string;
            original_filename: string;
            mime_type: string;
            size_bytes: number;
            /** @enum {string} */
            status: "pending" | "scanning" | "processing" | "ready" | "rejected" | "failed";
            /** @enum {string} */
            scan_status: "pending" | "clean" | "infected" | "failed";
            /** Format: date-time */
            replaced_at: string | null;
            /**
             * Format: date-time
             * @description UTC ISO-8601 timestamp.
             */
            created_at: string;
            /**
             * Format: date-time
             * @description UTC ISO-8601 timestamp.
             */
            updated_at: string;
        };
        DocumentPage: {
            data: components["schemas"]["DocumentResponse"][];
            pagination: components["schemas"]["Pagination"];
        };
        DocumentUploadPolicy: {
            max_size_bytes: number;
            allowed_mime_types: string[];
            allowed_document_types: components["schemas"]["DocumentType"][];
            accepted_extensions: string[];
        };
        DocumentRename: {
            display_name: string;
        };
        SignedDocumentUrlResponse: {
            /**
             * Format: uri
             * @description Short-lived signed download URL; never persist or share it.
             */
            url: string;
            /**
             * Format: date-time
             * @description UTC ISO-8601 timestamp.
             */
            expires_at: string;
        };
        DocumentReadinessItem: {
            required_document: string;
            ready: boolean;
            matched_document_ids: string[];
            /**
             * @description Readiness mapping never shares private documents externally.
             * @constant
             */
            shared_externally: false;
        };
        ApplicationDocumentReadiness: {
            /** Format: uuid */
            application_id: string;
            scholarship_title: string;
            items: components["schemas"]["DocumentReadinessItem"][];
        };
        DocumentReadinessResponse: {
            applications: components["schemas"]["ApplicationDocumentReadiness"][];
            /**
             * Format: date-time
             * @description UTC ISO-8601 timestamp.
             */
            updated_at: string;
        };
        /** @enum {string} */
        ScholarshipStudyLevel: "undergraduate" | "postgraduate" | "doctoral" | "other";
        /** @enum {string} */
        FundingType: "full" | "partial" | "tuition" | "stipend" | "research" | "other";
        /** @enum {string} */
        EligibilityStatus: "eligible" | "potentially_eligible" | "ineligible" | "unknown";
        EligibilityAssessment: {
            status: components["schemas"]["EligibilityStatus"];
            summary: string;
            reasons: string[];
            missing_facts: string[];
        };
        ScholarshipProvenance: {
            source_name: string;
            /** Format: uri */
            source_url: string;
            /** Format: date-time */
            ingested_at: string;
            /** Format: date-time */
            last_checked_at: string;
        };
        ScholarshipResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            provider: string;
            description?: string | null;
            amount?: number | null;
            currency?: string | null;
            funding_type: components["schemas"]["FundingType"];
            funding_summary?: string | null;
            study_levels: components["schemas"]["ScholarshipStudyLevel"][];
            fields_of_study: string[];
            destination_countries: string[];
            nationality_requirements: string[];
            residency_requirements: string[];
            /** Format: date */
            deadline: string | null;
            eligibility_summary?: string | null;
            eligibility: components["schemas"]["EligibilityAssessment"];
            requirements: string[];
            required_documents: string[];
            /** Format: uri */
            source_url: string;
            /** Format: uri */
            application_url?: string | null;
            provenance: components["schemas"]["ScholarshipProvenance"];
            /** Format: date-time */
            verified_at: string | null;
            saved: boolean;
            /** @enum {string} */
            status: "published" | "closed";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ScholarshipPage: {
            data: components["schemas"]["ScholarshipResponse"][];
            pagination: components["schemas"]["Pagination"];
        };
        SavedScholarshipResponse: {
            /** Format: uuid */
            scholarship_id: string;
            saved: boolean;
            /** Format: date-time */
            updated_at: string;
        };
        ScholarshipReportCreate: {
            /** @enum {string} */
            reason: "expired" | "incorrect_deadline" | "incorrect_eligibility" | "broken_source" | "other";
            details?: string | null;
        };
        ScholarshipReportResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            scholarship_id: string;
            /** @enum {string} */
            status: "received";
            /** Format: date-time */
            created_at: string;
        };
        ScoreComponent: {
            /** @enum {string} */
            name: "academics" | "eligibility_fit" | "interests_goals" | "experience" | "readiness_timing";
            score: number;
            weight: number;
        };
        MissingProfileFact: {
            field: string;
            question: string;
        };
        MatchExplanation: {
            why_this_matches: string[];
            what_may_block_you: string[];
            missing_information: components["schemas"]["MissingProfileFact"][];
            next_actions: string[];
        };
        RequirementEvidence: {
            label: string;
            detail: string;
            /** @enum {string} */
            basis: "verified_requirement" | "inferred_relevance" | "profile_unknown" | "requirement_not_met";
            /** Format: uri */
            source_url: string | null;
        };
        MatchResponse: {
            /** Format: uuid */
            id: string;
            rank: number;
            scholarship: components["schemas"]["ScholarshipResponse"];
            /** @description Relative profile-to-scholarship fit score; never a probability of winning. */
            score: number;
            /** @description Confidence in the score inputs based on profile and requirement completeness; never a probability of winning. */
            confidence: number;
            score_components: components["schemas"]["ScoreComponent"][];
            requirement_evidence: components["schemas"]["RequirementEvidence"][];
            deterministic_explanation: components["schemas"]["MatchExplanation"];
            ai_explanation: components["schemas"]["MatchExplanation"] | null;
            reasons?: string[];
            gaps?: string[];
            /** @enum {string} */
            explanation_status: "pending" | "ready" | "unavailable";
            algorithm_version: string;
            /** @enum {string} */
            calculation_status: "current" | "stale";
            stale_reasons: string[];
            /** Format: date-time */
            calculated_at: string;
        };
        MatchPage: {
            data: components["schemas"]["MatchResponse"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** @enum {string} */
        ApplicationStatus: "saved" | "preparing" | "ready" | "submitted" | "interview" | "awarded" | "unsuccessful" | "withdrawn";
        ApplicationCreate: {
            /** Format: uuid */
            scholarship_id: string;
            status?: components["schemas"]["ApplicationStatus"];
            notes?: string | null;
        };
        ApplicationUpdate: {
            status?: components["schemas"]["ApplicationStatus"];
            notes?: string | null;
        };
        ChecklistItemUpdate: {
            completed: boolean;
        };
        ApplicationChecklistItem: {
            /** Format: uuid */
            id: string;
            label: string;
            required: boolean;
            completed: boolean;
            /**
             * Format: date-time
             * @description UTC ISO-8601 timestamp.
             */
            updated_at: string;
        };
        ApplicationReminderWrite: {
            /**
             * Format: date-time
             * @description UTC ISO-8601 timestamp.
             */
            remind_at: string;
            /** @description IANA timezone used when the reminder was entered. */
            timezone: string;
        };
        ApplicationReminder: components["schemas"]["ApplicationReminderWrite"] & {
            /**
             * Format: date-time
             * @description UTC ISO-8601 timestamp.
             */
            created_at: string;
            /**
             * Format: date-time
             * @description UTC ISO-8601 timestamp.
             */
            updated_at: string;
        };
        /** @description Append-only audit record; status-history mutations are not exposed. */
        ApplicationStatusHistoryItem: {
            /** Format: uuid */
            id: string;
            from_status: components["schemas"]["ApplicationStatus"] | null;
            to_status: components["schemas"]["ApplicationStatus"];
            /**
             * Format: date-time
             * @description UTC ISO-8601 timestamp.
             */
            changed_at: string;
        };
        ApplicationResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            scholarship_id: string;
            scholarship: components["schemas"]["ScholarshipResponse"];
            status: components["schemas"]["ApplicationStatus"];
            /** @description Server-authoritative next states for this application. */
            allowed_transitions: components["schemas"]["ApplicationStatus"][];
            checklist: components["schemas"]["ApplicationChecklistItem"][];
            document_readiness: components["schemas"]["DocumentReadinessItem"][];
            status_history: components["schemas"]["ApplicationStatusHistoryItem"][];
            reminder: components["schemas"]["ApplicationReminder"] | null;
            notes: string | null;
            /**
             * Format: date-time
             * @description UTC ISO-8601 timestamp when a precise deadline is known.
             */
            deadline_at: string | null;
            /** @description Provider-published IANA timezone when known. */
            deadline_timezone: string | null;
            /** Format: date-time */
            submitted_at: string | null;
            /**
             * Format: date-time
             * @description UTC ISO-8601 timestamp.
             */
            created_at: string;
            /**
             * Format: date-time
             * @description UTC ISO-8601 timestamp.
             */
            updated_at: string;
        };
        ApplicationPage: {
            data: components["schemas"]["ApplicationResponse"][];
            pagination: components["schemas"]["Pagination"];
        };
        ApplicationDeadline: {
            /** Format: uuid */
            application_id: string;
            /** Format: uuid */
            scholarship_id: string;
            title: string;
            provider: string;
            status: components["schemas"]["ApplicationStatus"];
            /** Format: date */
            deadline_date: string | null;
            /** Format: date-time */
            deadline_at: string | null;
            /** @description Provider-published IANA timezone when known. */
            source_timezone: string | null;
            /** Format: uri */
            source_url: string;
        };
        ApplicationDeadlinePage: {
            data: components["schemas"]["ApplicationDeadline"][];
            pagination: components["schemas"]["Pagination"];
        };
        JobResponse: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "queued" | "running" | "completed" | "failed";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            matches_updated_at?: string | null;
            error_code?: string | null;
        };
        MatchFeedbackCreate: {
            useful: boolean;
            /** @enum {string} */
            reason: "accurate" | "unclear" | "missing_context" | "incorrect" | "not_relevant" | "other";
            details?: string | null;
        };
        MatchFeedbackResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            match_id: string;
            /** @enum {string} */
            status: "received";
            /** Format: date-time */
            created_at: string;
        };
        IngestionRunCreate: {
            source: string;
            /** Format: uri */
            source_url?: string | null;
            /** @default false */
            dry_run: boolean;
        };
        IngestionRunResponse: {
            /** Format: uuid */
            id: string;
            source: string;
            /** @enum {string} */
            status: "queued" | "running" | "completed" | "failed" | "cancelled";
            counters: {
                fetched: number;
                created: number;
                updated: number;
                skipped: number;
                failed: number;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            completed_at?: string | null;
        };
    };
    responses: {
        /** @description Malformed request or cursor. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Bearer token is missing or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated actor lacks the required role or permission. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource was not found or is not visible to the actor. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description State, duplicate resource, or idempotency conflict. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Uploaded file exceeds the configured limit. */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Uploaded file type is not allowed. */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Request fields failed semantic validation. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Request rate exceeded. */
        RateLimited: {
            headers: {
                /** @description Seconds until the client should retry. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Unexpected server error with no sensitive implementation details. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description Searches title, provider, field, and normalized description. */
        ScholarshipQuery: string;
        StudyLevel: components["schemas"]["ScholarshipStudyLevel"];
        Field: string;
        Destination: string;
        Nationality: string;
        Residency: string;
        FundingType: components["schemas"]["FundingType"];
        DeadlineFrom: string;
        DeadlineTo: string;
        Verified: boolean;
        ScholarshipSort: "relevance" | "deadline" | "recently_verified" | "funding_amount";
        /** @description Opaque cursor returned as `pagination.next_cursor`; clients must not parse it. */
        Cursor: string;
        Limit: number;
        /** @description Caller-generated opaque key. Do not include credentials or personal data. */
        IdempotencyKey: string;
        ScholarshipId: string;
        ApplicationId: string;
        RunId: string;
        DocumentId: string;
        ChecklistItemId: string;
        JobId: string;
    };
    requestBodies: never;
    headers: {
        /** @description `true` when this response replays a completed request. */
        IdempotencyReplayed: boolean;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    replaceProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileWrite"];
            };
        };
        responses: {
            /** @description Profile replaced. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    listProfileDocuments: {
        parameters: {
            query?: {
                /** @description Opaque cursor returned as `pagination.next_cursor`; clients must not parse it. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Private document page. No storage paths or permanent object URLs are returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    uploadProfileDocument: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated opaque key. Do not include credentials or personal data. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    document_type: components["schemas"]["DocumentType"];
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Upload accepted for processing. */
            202: {
                headers: {
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getDocumentUploadPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current approved types, MIME types, and maximum file size. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadPolicy"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getDocumentReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document readiness grouped by tracked application. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentReadinessResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    replaceProfileDocument: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated opaque key. Do not include credentials or personal data. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                document_id: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Replacement accepted for scanning and processing. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteProfileDocument: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated opaque key. Do not include credentials or personal data. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                document_id: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document deleted. Readiness mappings are recalculated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    renameProfileDocument: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated opaque key. Do not include credentials or personal data. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                document_id: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentRename"];
            };
        };
        responses: {
            /** @description Document renamed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    createDocumentDownloadUrl: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated opaque key. Do not include credentials or personal data. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                document_id: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Short-lived URL created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedDocumentUrlResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    listScholarships: {
        parameters: {
            query?: {
                /** @description Searches title, provider, field, and normalized description. */
                q?: components["parameters"]["ScholarshipQuery"];
                study_level?: components["parameters"]["StudyLevel"];
                field?: components["parameters"]["Field"];
                destination?: components["parameters"]["Destination"];
                nationality?: components["parameters"]["Nationality"];
                residency?: components["parameters"]["Residency"];
                funding_type?: components["parameters"]["FundingType"];
                deadline_from?: components["parameters"]["DeadlineFrom"];
                deadline_to?: components["parameters"]["DeadlineTo"];
                verified?: components["parameters"]["Verified"];
                sort?: components["parameters"]["ScholarshipSort"];
                /** @description Opaque cursor returned as `pagination.next_cursor`; clients must not parse it. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scholarship page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScholarshipPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getScholarship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scholarship_id: components["parameters"]["ScholarshipId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scholarship found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScholarshipResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listRelatedScholarships: {
        parameters: {
            query?: {
                /** @description Opaque cursor returned as `pagination.next_cursor`; clients must not parse it. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                scholarship_id: components["parameters"]["ScholarshipId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Related scholarship page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScholarshipPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    saveScholarship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scholarship_id: components["parameters"]["ScholarshipId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scholarship saved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedScholarshipResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    unsaveScholarship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scholarship_id: components["parameters"]["ScholarshipId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scholarship removed from saved list. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    reportScholarship: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated opaque key. Do not include credentials or personal data. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                scholarship_id: components["parameters"]["ScholarshipId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScholarshipReportCreate"];
            };
        };
        responses: {
            /** @description Report received. */
            201: {
                headers: {
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScholarshipReportResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    listMatches: {
        parameters: {
            query?: {
                /** @description Opaque cursor returned as `pagination.next_cursor`; clients must not parse it. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Match page, ordered by descending score with a stable ID tie-breaker. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    recalculateMatches: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated opaque key. Do not include credentials or personal data. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recalculation queued. */
            202: {
                headers: {
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getMatchRecalculationJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recalculation job status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scholarship_id: components["parameters"]["ScholarshipId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Match found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    createMatchFeedback: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated opaque key. Do not include credentials or personal data. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                scholarship_id: components["parameters"]["ScholarshipId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchFeedbackCreate"];
            };
        };
        responses: {
            /** @description Feedback received. */
            201: {
                headers: {
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchFeedbackResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    listApplications: {
        parameters: {
            query?: {
                /** @description Opaque cursor returned as `pagination.next_cursor`; clients must not parse it. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listApplicationDeadlines: {
        parameters: {
            query?: {
                /** @description Opaque cursor returned as `pagination.next_cursor`; clients must not parse it. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deadline page ordered chronologically with undated items last. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDeadlinePage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createApplication: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated opaque key. Do not include credentials or personal data. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreate"];
            };
        };
        responses: {
            /** @description Application created. */
            201: {
                headers: {
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    updateApplication: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated opaque key. Do not include credentials or personal data. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                application_id: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationUpdate"];
            };
        };
        responses: {
            /** @description Application updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    updateApplicationChecklistItem: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated opaque key. Do not include credentials or personal data. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                application_id: components["parameters"]["ApplicationId"];
                checklist_item_id: components["parameters"]["ChecklistItemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChecklistItemUpdate"];
            };
        };
        responses: {
            /** @description Application with refreshed checklist and readiness. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    setApplicationReminder: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated opaque key. Do not include credentials or personal data. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                application_id: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationReminderWrite"];
            };
        };
        responses: {
            /** @description Application with updated reminder. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteApplicationReminder: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated opaque key. Do not include credentials or personal data. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                application_id: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application with reminder removed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    createIngestionRun: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated opaque key. Do not include credentials or personal data. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestionRunCreate"];
            };
        };
        responses: {
            /** @description Ingestion run queued. */
            202: {
                headers: {
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRunResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getIngestionRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingestion run found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRunResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
}
